name: linux
on: push
  # The build name to use instead of "custom_build"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls && pwd 
      #- run: /scripts/gitlab-ci/before_script.sh
      - run: ls
      - run: cd scripts
      - run: "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_editor.sh" 
      - run: "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_templates.sh debug"
      - run: "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_templates.sh release"

